---
- name: Dynamic inventory source update
  hosts: "{{ HOSTS | default('control[0]') }}"
  connection: local
  vars:
    # controller_hostname: "{{ hostvars[inventory_hostname].ansible_host }}"
    controller_hostname: "{{ lookup('env', 'TOWER_HOST') }}"
    controller_validate_certs: false

  tasks:
    - name: Update inventory via source "EC2 Dynamic Source - {{ rhel_inventory_group }}"
      ansible.controller.inventory_source_update:
        name: "EC2 Dynamic Source - {{ rhel_inventory_group }}"
        inventory: Workshop Inventory
        organization: Default
...
