---
- name: Upgrade
  hosts: "{{ ripu_pet_name is defined | ternary( ripu_pet_name, rhel_inventory_group | default(omit) ) }}"
  strategy: free
  become: true
  force_handlers: true
  # vars:
  #   ansible_python_interpreter: /usr/libexec/platform-python
  tasks:
    - name: Perform OS upgrade
      ansible.builtin.import_role:
        name: infra.leapp.upgrade
...
